const GET_CURRENT_USER_START = '@auth/GET_CURRENT_USER_START';
const GET_CURRENT_USER_SUCCESS = '@auth/GET_CURRENT_USER_SUCCESS';
const GET_CURRENT_USER_ERROR = '@auth/GET_CURRENT_USER_ERROR ';

// const GET_USER_HABIT_START = "@auth/GET_USER_INFO_START";
// const GET_USER_HABIT_SUCCESS = "@auth/GET_USER_INFO_SUCCESS";
// const GET_USER_HABIT_ERROR = "@auth/GET_USER_INFO_ERROR";

const LOGOUT_START = '@auth/LOGOUT_START ';
const LOGOUT_SUCCESS = '@auth/LOGOUT_SUCCESS';
const LOGOUT_ERROR = '@auth/LOGOUT_ERROR';

const GET_DONE_HABITS = '@auth/GET_DONE_HABIT';
export default {
  GET_CURRENT_USER_START,
  GET_CURRENT_USER_SUCCESS,
  GET_CURRENT_USER_ERROR,

  // GET_USER_HABIT_START,
  // GET_USER_HABIT_SUCCESS,
  // GET_USER_HABIT_ERROR,

  LOGOUT_START,
  LOGOUT_SUCCESS,
  LOGOUT_ERROR,
  GET_DONE_HABITS,
};
